### PR TITLE
Restructure and tooling

### PR DESCRIPTION
**Pull request by darrelhong**
Since this repo is meant to be a framework for new projects, i thought it would be good idea to update it to make use of more modern tooling available in the node/ts ecosystem. As it's a skeleton project, it's easier to change things around and the functionality can be validated as well. I'll list the changes here in summary but it might be easier to go through each commit to see what has changed.

### Changes
- Folder structure - placed all projects into /packages folder in line with js monorepo conventions (facilitates using tools like yarn or npm)
- use npm workspaces to manage projects and dependencies
- resolve dependency conflicts with react-refresh
- "shared" package is used as a local dependency
- use ts project references
- ~~"shared" now publishes ES modules~~ (backend project doesnt support esm) 

I have tested the changes and local development/unit tests are working, but might have missed out other things. One concern would be with the docker deployment, that might need further testing and verification.

Other things that could be added perhaps are dockerising the development workflow and making use of Vite/esbuild in the frontend.

Would love to hear your thoughts @njenwei @LoneRifle

### CODE REVIEW

**Review by LoneRifle — CHANGES_REQUESTED** [review]
First, thanks for this PR as well as opengovsg/FormSG#4414 and opengovsg/GoGovSG#1901!

There are quite a number of things to look through here. Given the work week has yet to start, I'll look into testing this properly tomorrow, but it looks promising.

Something you might want to work on in the meantime that prompted the request for changes:
- package naming. Given that this will be used as a template for other products, I'm not sure that the package name format `@opengovsg/*` would work, since the resulting names would come across as a single backend/frontend/shared package for all of OGP! Consider a different naming scheme, perhaps ~`@/*`~ (EDIT: okay, not this, but a generic enough name to indicate that this is just the project-specific packages) or similar.

Other, less urgent things:
- commit messages - not everything is a `feat:`; make use of the other Conventional Commit keywords to more accurately describe the nature of the commits
- the number of files and changes involved in the PR is way too high. I would let it slide this time, but in future, if a single PR must effect this much change, consider reorganising the commit log using interactive rebase, to facilitate review.

**Comment by LoneRifle** [comment]
> Other things that could be added perhaps are dockerising the development workflow and making use of Vite/esbuild in the frontend.
I explicitly chose against dockerising the dev workflow, given the experiences that the FormSG team had with related spin-up times for dev testing on local machine, which had a drag on development velocity. My own experience informs me that a more convenient setup would involve dockerising the surrounding infra, and running the application on local machine, making it somewhat easier to reason about and if needed, to inspect the backend with Chrome Dev Tools.

We don't have to use Vite for now; react-scripts/webpack is adequate for our needs, given its maturity and familiarity

**Review by LoneRifle — CHANGES_REQUESTED** [review]
So, I've tried this on my own dev environment, and found that changes to `shared/` do not immediately propagate to either the build process or VSCode. To reproduce, run `npm run dev`, make a change to GenerateOtpDto by renaming the `email` property to `mail`, and then make corresponding changes throughout the front and backend codebases. You will then observe that VSCode does not recognise the type of the renamed property, and neither does webpack.

I don't think I am comfortable with both the size of this PR or the notion of using workspaces for now, so I will close this PR. 

Thanks nonetheless for trying out more recent practices and a fresh approach to organise the codebase!

@njenwei - as discussed.

**Comment by darrelhong** [comment]
Seeing as the PR is closed I will not make any updates but I would still like to respond to the comments given.

To my understanding, the scope simply informs what org/group of packages a package belongs, and when creating a project from this template, the package names should definitely be renamed, e.g. @opengovsg/formsg-client. For the host projects that are not going to be used by other packages or published, I guess it doesn't really matter. The main motivation for addig scope is for the "shared" library, so imports look like `... from "@opengovsg/shared"` instead of `... from "shared"`.

With regards to commit type, depending on how you view it, I would either all of them either as feat or chore. Since this is not a production project, changes to tooling can be seen as a feature. Maybe to get really semantic, perhaps the commit where files are only being moved should be classified as refactor, though it wouldn't appear in git blame.

Agree that the commits could be reordered to group related ones together. As for the size of the PR, actually the number of meaningful lines change is not a lot, and a large PR is unavoidable for refactor type cases.

Agree with vite, it's only if you really want to use latest and greatest FE tooling. It'll probably cause more issues when using npm packages that don't support it. With regards to CRA, I'm all for it but throw in other dependencies like craco or rewired and you can't "just update" to the the latest CRA anymore. So it's a balance of priorities.

On docker, i was wondering why the other projects have fully integrated docker in development while this does not. It's good to know the context behind this and I do think docker is more fit for the stateless side of things. I would also assume node has decent cross platform support, so using docker would not have much benefit and create more complications.

For the last point, i think the changes definitely need more tinkering to make sure it works on all systems. On my side I made sure that hot reload works in development which you can see in the demo below.

https://user-images.githubusercontent.com/39296145/183385455-1e3dbcf7-ffae-455f-ad03-f6129468dafd.mov

**Pull request closed without merging**
